[WIP] Ukrainian translation
LixieWulf/Allure pull request #51
Opened 2022-02-02 19:45 UTC by Chompycat

Created with love

2022-02-02 19:55 UTC, Prosta4okua requested changes

2022-02-02 19:55 UTC, Prosta4okua commented on bundles/bundle_uk_UA.properties
> +block.exotic-mod-advanced-melter.name = Покращена плавильня
Advance - Просунута/Передова

2022-02-02 19:55 UTC, Prosta4okua commented on bundles/bundle_uk_UA.properties
> +block.exotic-mod-amethyst-refiner.description = Вирізує аметисти в кристальні пластини
Вирізає*

2022-02-02 19:55 UTC, Prosta4okua commented on bundles/bundle_uk_UA.properties
> +block.exotic-mod-extractor.description = Витягує анден який залишився в брухті. Потребує води щоб зламати брухт.
Що таке анден?

2022-02-02 19:55 UTC, Prosta4okua commented on bundles/bundle_uk_UA.properties
> +block.exotic-mod-furnace.description = Сплавляє кремній та свинець разом щоб отримати территовий сплав.
Кома перед щоб.

2022-02-02 19:55 UTC, Prosta4okua commented on bundles/bundle_uk_UA.properties
> +block.exotic-mod-industrial-compressor.name = Індустріальний компрессор
Компресор з одною с.

2022-02-02 19:55 UTC, Prosta4okua commented on bundles/bundle_uk_UA.properties
> +block.exotic-mod-industrial-compressor.description = Стискає пластаній набагато швидше, ніж звичайний компрессор. Потребує стручки спор для нафти.
Компресор з одною с.

2022-02-02 19:55 UTC, Prosta4okua commented on bundles/bundle_uk_UA.properties
> +block.exotic-mod-shadow-infuser.description = Забирає велику кількість сучасних матеріалів і поєднує їх властивості для створення надзвичайно потужного сплаву.
`Їхні` замість `їх`

2022-02-02 19:55 UTC, Prosta4okua commented on bundles/bundle_uk_UA.properties
> +block.exotic-mod-supercoolant-mixer.name = Перемішувач суперохлоджувальної рідини
Може ліпше змішувач?

2022-02-02 19:55 UTC, Prosta4okua commented on bundles/bundle_uk_UA.properties
> +block.exotic-mod-supercoolant-mixer.description = Додає дрібний порошок аметисту з кріогенною рідиною для створення більш ефективної охолоджуючої рідини.
Додає щось до чогось. Охолоджувальної*. Активні дієприкметники нізя.

2022-02-02 19:55 UTC, Prosta4okua commented on bundles/bundle_uk_UA.properties
> +block.exotic-mod-tri-weaver.description = Покращена версія фазофого ткача. Виробляє великі об'єми фазової тканини з кращою еффекетивністю. Потребує охолоджувача.
Advance - передова чи просунута
Improve - поліпшувати
Покращена прибирай. 

Ефективність з одною ф.

Потрібен охолоджувач ліпше.

2022-02-02 19:55 UTC, Prosta4okua commented on bundles/bundle_uk_UA.properties
> +block.exotic-mod-tungsten-refiner.description = Витягує вольфрам з вольфрамітового брухту для використання в юнітах.
Unit - одиниця

2022-02-02 19:55 UTC, Prosta4okua commented on bundles/bundle_uk_UA.properties
> +block.exotic-mod-absorber-wall.name = Поглинаюча стіна
Активний дієприкметник

2022-02-02 19:55 UTC, Prosta4okua commented on bundles/bundle_uk_UA.properties
> +block.exotic-mod-absorber-wall.description = Слабкий захисний блок, здатний відновлюватися за рахунок енергії.
https://onlinecorrector.com.ua/uk/%D0%B7%D0%B0-%D0%BA%D0%BE%D1%88%D1%82-%D0%B7%D0%B0%D0%B2%D0%B4%D1%8F%D0%BA%D0%B8-%D0%B2%D0%BD%D0%B0%D1%81%D0%BB%D1%96%D0%B4%D0%BE%D0%BA/

2022-02-02 19:55 UTC, Prosta4okua commented on bundles/bundle_uk_UA.properties
> +block.exotic-mod-absorber-wall-large.description = Слабкий захисний блок, здатний відновлюватися за рахунок енергії.
https://onlinecorrector.com.ua/uk/%D0%B7%D0%B0-%D0%BA%D0%BE%D1%88%D1%82-%D0%B7%D0%B0%D0%B2%D0%B4%D1%8F%D0%BA%D0%B8-%D0%B2%D0%BD%D0%B0%D1%81%D0%BB%D1%96%D0%B4%D0%BE%D0%BA/

2022-02-02 19:55 UTC, Prosta4okua commented on bundles/bundle_uk_UA.properties
> +block.exotic-mod-amethyst-wall.description = Захищає конструкції від ворожих снарядів. Помірно міцний.
Помірно міцн**а**, бо стіна

2022-02-02 19:55 UTC, Prosta4okua commented on bundles/bundle_uk_UA.properties
> +block.exotic-mod-baenite-wall-large.name = Велика Баєнітова стіна
Чому друге слово з великої?

2022-02-02 19:55 UTC, Prosta4okua commented on bundles/bundle_uk_UA.properties
> +block.exotic-mod-buffer-wall-large.name = Large Buffer Wall
Не перекладено

2022-02-02 19:55 UTC, Prosta4okua commented on bundles/bundle_uk_UA.properties
> +block.exotic-mod-distribution-wall.description = Помірно міцний оборонний блок. Транспортує та розподіляє рідини до веж, торкаючись стін.
Tower - башта, лише. У грі лише башти. Вежі то дещо інше.

2022-02-02 19:55 UTC, Prosta4okua commented on bundles/bundle_uk_UA.properties
> +block.exotic-mod-draconium-wall-huge.description = Ізолює від блискавки та лазерів. Відбиває кулі з фазовим покриттям.
Або прибирай з або заміняй на `за допомогою`

2022-02-02 19:55 UTC, Prosta4okua commented on bundles/bundle_uk_UA.properties
> +block.exotic-mod-exotic-item-source.description = Тільки для пісочниці джерело предметів з більшим здоров'ям
Крапка.

2022-02-02 19:55 UTC, Prosta4okua commented on bundles/bundle_uk_UA.properties
> +block.exotic-mod-floating-conveyor.name = Левітуючий конвейер
Активний дієприкметник.

2022-02-02 19:55 UTC, Prosta4okua commented on bundles/bundle_uk_UA.properties
> +block.exotic-mod-floating-junction.name = Левітуюче перехрестя
Активний дієприкметник.

2022-02-02 19:55 UTC, Prosta4okua commented on bundles/bundle_uk_UA.properties
> +block.exotic-mod-floating-sorter.name = Левітуючий сортувальник
Активний дієприкметник.

2022-02-02 20:01 UTC, Chompycat commented on bundles/bundle_uk_UA.properties
> +block.exotic-mod-extractor.description = Витягує анден який залишився в брухті. Потребує води щоб зламати брухт.
Ресурс

2022-02-03 02:22 UTC, BlueWolf3682 commented
ill wait for prosta to give the go ahead on this one

2022-02-03 21:18 UTC, Prosta4okua requested changes

2022-02-03 21:18 UTC, Prosta4okua commented on bundles/bundle_uk_UA.properties
> +weather.exotic-mod-healing-winds.name = Лікуючий вітер
Активний дієприкметник

2022-02-03 21:18 UTC, Prosta4okua commented on bundles/bundle_uk_UA.properties
> +item.exotic-mod-shadow.description = Дивний невідомий матеріал, утворений шляхом поєднання інших матеріалів та їх властивостей. Надзвичайно потужний.
[Їх чи Їхній ](https://onlinecorrector.com.ua/uk/%D1%97%D1%85-%D1%96-%D1%97%D1%85%D0%BD%D1%96%D0%B9/)

2022-02-03 21:18 UTC, Prosta4okua commented on bundles/bundle_uk_UA.properties
> +item.exotic-mod-forge-plating.description = Таємниче покриття, яке повсюдно зустрічається в ядрах FTL. Допомагає в дослідженні передових структур і бойових одиниць.
Було б цікаво дізнатися що за FTL 🤔

2022-02-03 21:18 UTC, Prosta4okua commented on bundles/bundle_uk_UA.properties
> +block.exotic-mod-blue-sand-baenara.name = Синій пісок з Баенарою
Мала літера

2022-02-03 21:18 UTC, Prosta4okua commented on bundles/bundle_uk_UA.properties
> +block.exotic-mod-hyperdrive-radiator.description = Проектує поле, здатне сильно підвищувати структури. Для роботи потрібні введення матеріалу та охолоджуючої рідини.
охолодж**ую**ча. Півдишувати структури?

2022-02-03 21:18 UTC, Prosta4okua commented on bundles/bundle_uk_UA.properties
> +block.exotic-mod-force-barricade.description = Випромінює масивне силове поле. Надзвичайно міцний, хоча повільно відновлюється після збою.
Міцна*

2022-02-03 21:18 UTC, Prosta4okua commented on bundles/bundle_uk_UA.properties
> +block.exotic-mod-core-requiem.description = Остання ітерація ядер Exotic Mod. Практично незнищенне, це ядро надзвичайно дороге і рекомендоване для запусків у найнебезпечніші сектори.
Я думаю "Фінальна версія" звучить ліпше.

2022-02-03 21:18 UTC, Prosta4okua commented on bundles/bundle_uk_UA.properties
> +block.exotic-mod-bluewolframite-mender.description = Невеликий синьольфрамітовий ремонтник. Використовує передові електромагнітні засоби для швидкого відновлення пошкоджень в сусідніх структурах. Для
Швидке відновлення пошкодження? Для повного ефекту треба якось замінити мабуть

2022-02-03 21:18 UTC, Prosta4okua commented on bundles/bundle_uk_UA.properties
> +block.exotic-mod-shielded-wall.description = Міцна стіна, яка випромінює невелике сильне силове поле. Для роботи потрібне живлення.
Енергія*

2022-02-03 21:18 UTC, Prosta4okua commented on bundles/bundle_uk_UA.properties
> +block.exotic-mod-draconium-wall-large.description = Ізолює від блискавки та лазерів. Відбиває кулі завдяки фазовоиу покриттю.
фазово**м**у

2022-03-10 16:41 UTC, BlueWolf3682 commented
*kick kick*

2022-03-10 18:30 UTC, Prosta4okua commented
> _kick kick_

We are kinda busy. Russo-Ukrainian war.

2022-05-03 12:25 UTC, BlueWolf3682 commented
Closing due to inactivity and upcoming content overhaul.
If you want to make a full translation PR, I suggest waiting a couple weeks at least.

2022-05-03 12:25 UTC, closed without merging